const disabledRule =
{
  'at-rule-allowed-list': null,
  'at-rule-property-required-list': null,
  'color-no-hex': null,
  'comment-pattern': null,
  'comment-word-disallowed-list': null,
  'custom-media-pattern': null,
  'custom-property-pattern': null,
  'declaration-property-max-values': null,
  'declaration-property-unit-allowed-list': null,
  'declaration-property-unit-disallowed-list': null,
  'declaration-property-value-allowed-list': null,
  'declaration-property-value-disallowed-list': null,
  'declaration-property-value-no-unknown': null,
  'font-family-no-missing-generic-family-keyword': null,
  'function-allowed-list': null,
  'function-disallowed-list': null,
  'function-url-scheme-allowed-list': null,
  'function-url-scheme-disallowed-list': null,
  'keyframes-name-pattern': null,
  'media-feature-name-allowed-list': null,
  'media-feature-name-disallowed-list': null,
  'media-feature-name-unit-allowed-list': null,
  'media-feature-name-value-allowed-list': null,
  'property-allowed-list': null,
  'property-disallowed-list': null,
  'rule-selector-property-disallowed-list': null,
  'selector-attribute-name-disallowed-list': null,
  'selector-attribute-operator-allowed-list': null,
  'selector-attribute-operator-disallowed-list': null,
  'selector-combinator-allowed-list': null,
  'selector-combinator-disallowed-list': null,
  'selector-disallowed-list': null,
  'selector-id-pattern': null,
  'selector-max-attribute': null,
  'selector-max-class': null,
  'selector-max-combinators': null,
  'selector-max-pseudo-class': null,
  'selector-max-specificity': null,
  'selector-max-type': null,
  'selector-max-universal': null,
  'selector-nested-pattern': null,
  'selector-pseudo-class-allowed-list': null,
  'selector-pseudo-class-disallowed-list': null,
  'selector-pseudo-element-allowed-list': null,
  'selector-pseudo-element-disallowed-list': null,
  'time-min-milliseconds': null,
  'unit-allowed-list': null,
  'unit-disallowed-list': null
};

export { disabledRule };