name: ❓ Question
description: question about the repo, the docs or other
labels: ['❓ question']
title: '[❓]'
body:
- type: markdown
  attributes:
    value: |
      Please make a question related with the project and not outside the scope of this
- type: textarea
  id: question
  attributes:
    description: 'A clear and concise description of your question'
    label: Question
  validations:
    required: true